name: restaurant_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  http: ^1.5.0
  logger: ^2.6.1
  intl: ^0.20.2
  sqflite: ^2.4.2
  shared_preferences: ^2.5.3
  flutter_timezone: ^5.0.0
  timezone: ^0.10.1
  flutter_local_notifications: ^19.4.2
  test: ^1.26.2
  equatable: ^2.0.7
  mockito: ^5.5.0
  build_runner: ^2.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
